### ISSUE TITLE
Power APP PMM - Aggiungere bagde , nome e cognome del dipendente loggato in alto a destra (WI 18347)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#534]
![Image](https://github.com/user-attachments/assets/74f27f01-bb91-4040-a600-7d6b6d752149)

**Comment by Matteo-Parlato-EOS** [comment]
Ciao Simone, abbiamo aggiunto nuovamente l'indicazione del nr. e nome impiegato:

![Image](https://github.com/user-attachments/assets/900ea54d-a6d9-494b-8c0b-74ccec663d3b)

Questo il codice per riportare le modifiche nei progetti custom:

```
Da aggiungere in DashboardScreen_HeaderContainer
 
- DashboardScreen_HeaderContainer_Group1_Container:
    Control: GroupContainer@1.3.0
    Variant: AutoLayout
    Properties:
      DropShadow: =DropShadow.None
      Fill: =ColorFade(AppThemeScheme.PrimaryColor, -15%)
      Height: =Parent.Height
      LayoutAlignItems: =LayoutAlignItems.Stretch
      LayoutDirection: =LayoutDirection.Vertical
      LayoutMinHeight: =0
      LayoutMinWidth: =0
      PaddingRight: =10
      RadiusBottomLeft: =0
      RadiusBottomRight: =0
      RadiusTopLeft: =0
      RadiusTopRight: =0
      Width: =0
    Children:
      - DashboardScreen_EmployeeHintAltLabel:
          Control: Label@2.5.1
          Properties:
            Align: =Align.Right
            BorderColor: =Self.Color
            Color: =RGBA(255, 255, 255, 1)
            DisplayMode: =If(ControlsDisabled, DisplayMode.Disabled, DisplayMode.Edit)
            FillPortions: =1
            Font: =Font.'Segoe UI'
            FontWeight: =FontWeight.Bold
            LayoutMinHeight: =0
            LayoutMinWidth: =0
            Size: =AppThemeScheme.HintTextSize
            Text: =SelectedEmployee.employeeNo
            Visible: =!IsBlank(SelectedEmployee)
            Width: =0
            Wrap: =false
      - DashboardScreen_EmployeeSubtitle2Label:
          Control: Label@2.5.1
          Properties:
            Align: =Align.Right
            BorderColor: =Self.Color
            Color: =RGBA(255, 255, 255, 1)
            DisabledFill: =Self.Fill
            DisplayMode: =If(ControlsDisabled, DisplayMode.Disabled, DisplayMode.Edit)
            FillPortions: =2
            Font: =Font.'Segoe UI'
            LayoutMinHeight: =0
            LayoutMinWidth: =0
            Size: =If(App.ActiveScreen.Size <= 1, AppThemeScheme.DefaultTextSize, AppThemeScheme.Subtitle2TextSize)
            Text: =SelectedEmployee.employeeSearchName
            Width: =0
            Wrap: =false
```
